name: delivery_hero_flutter_study_case
description: A study case made with Flutter
repository: https://github.com/kaankoken/dhstudycase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: 3.0.3


dependencies:
  flutter:
    sdk: flutter

  # Theme
  google_fonts: 3.0.1
  cupertino_icons: 1.0.5
  auto_size_text: 3.0.0
  flutter_native_splash: 2.2.3+1

  # State management & Dependency Injection
  flutter_riverpod: 2.0.0-dev.9

  # Linter
  dart_code_metrics: 4.16.0

  # Annotation
  json_annotation: 4.5.0
  freezed_annotation: 2.0.3

  # Routing
  go_router: 4.0.0

  # Network
  retrofit: 3.0.1+1

  # Local Environment
  flutter_dotenv: 5.0.2

  # Utils
  flutter_localizations:
    sdk: flutter
  collection: 1.16.0
  intl: 0.17.0
  flutter_svg: 1.1.0
  fluttertoast: 8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: 2.0.1

  # Generator
  json_serializable: 6.2.0
  analyzer: 4.1.0
  build_runner: 2.1.11
  retrofit_generator: 4.0.1
  
  # Data Model
  freezed: 2.0.3+1


dependency_overrides:
  analyzer:


flutter:
  uses-material-design: true

  assets:
    - assets/